### PR TITLE
Capstone Project Version 1

### PR DESCRIPTION
**Pull request by Errytagedesign**
## Live Link 
[live website](https://budgetapp-2k4n.onrender.com/)

## Video Link 
[Presentation video](https://www.loom.com/share/b38b3ef1ddd14a4687d57186a68183ad?sid=9c7a3caf-3c8e-4dc9-bfd8-1151f756e909)

- Add Splash Screen:
- Add signup screen with validations
- Add login screen with validation
- Redirect user after signin in
- Show categories list page
- Add new Category 
- Click and view each categories
- Add transaction in each category
- Back button to navigate back to previous page

### CODE REVIEW

**Comment by binhussen** [comment]
@Errytagedesign kindly fix the broken `mit` lisense link in your readme file

**Comment by Errytagedesign** [comment]
> @Errytagedesign kindly fix the broken `mit` lisense link in your readme file

Done

**Comment by Errytagedesign** [comment]
Done

**Review by binhussen — APPROVED** [review]
Hi @Errytagedesign , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
IApproveSimonCowellGIF (6)

## Highlights
- Sticked Given Design ✔️
- Well Stractured Code ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
